### ISSUE TITLE
add events in the events page

### ISSUE THREAD

**Issue by Mudassirkhan2** [Bug-Bounty-Brigade/Bug-Bounty-Brigade-Main-Website#22]
add events in the events page

the information are in the below  post links 

https://www.linkedin.com/posts/bug-bounty-brigade_bugbountybrigade-informationdisclosure-cybersecurityjourney-activity-7096054108972871680--VuQ?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/bug-bounty-brigade_dear-bug-bounty-brigade-community-activity-7090208934963138560-qK7A?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/bug-bounty-brigade_bugbountybrigade-automatingbugbounty-cybersecurity-activity-7088091994794725376-vbJV?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/bug-bounty-brigade_bug-bounty-brigade-and-owasp-kaithal-collaboration-activity-7085920215363977216-i69y?utm_source=share&utm_medium=member_desktop

**Comment by Emilio-PdeA** [comment]
I would like to work on this. Can you assign it to me?

**Comment by Mudassirkhan2** [comment]
please go through contributing.md for successful  PR

**Comment by Emilio-PdeA** [comment]
I have two questions @Mudassirkhan2:

- Should the events should have certain order?
- How do I get the number of attendees?

**Comment by Mudassirkhan2** [comment]
-> yes according to the date it happended
--> https://www.youtube.com/@bugbountybrigade/videos      from here you can get the number of attendees
