### ISSUE TITLE
Correct event dates in the event page

### ISSUE THREAD

**Issue by Mudassirkhan2** [Bug-Bounty-Brigade/Bug-Bounty-Brigade-Main-Website#23]
Correct event dates in the event page.

In the images you can see the event dates which are not as same as present in the event page 

https://www.bugbountybrigade.tech/events

or you can refer  https://www.linkedin.com/company/bug-bounty-brigade/posts/?feedView=all

**Comment by Virtual4087** [comment]
i would like to work on this

**Comment by Mudassirkhan2** [comment]
i have assigned it to you . please  go through contributing.md  to make successful  PR.

**Comment by Virtual4087** [comment]
ok
