### ISSUE TITLE
add events in the events page

### ISSUE THREAD

**Issue by Mudassirkhan2** [Bug-Bounty-Brigade/Bug-Bounty-Brigade-Main-Website#27]
add events in the events page

the information are in the below post links

https://www.linkedin.com/posts/bug-bounty-brigade_exciting-announcement-join-bug-bounty-activity-7085316190109118465-2ePf?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/bug-bounty-brigade_bugbounty-cybersecurity-cloudsecurity-activity-7082791565147975680-5WAd?utm_source=share&utm_medium=member_desktop

https://www.linkedin.com/posts/bug-bounty-brigade_attention-bug-bounty-brigade-community-activity-7076137918477578240-DjX9?utm_source=share&utm_medium=member_desktop

**Comment by iamsravya** [comment]
Hi, I can do it. Please assign it to me.
Thank you.

**Comment by iamsravya** [comment]
@Mudassirkhan2 i have completed it and raised a pull request. Please give review and if everything is ok, merge it.
Thank you.
