### ISSUE TITLE
Add events in events page

### ISSUE THREAD

**Issue by Mudassirkhan2** [Bug-Bounty-Brigade/Bug-Bounty-Brigade-Main-Website#31]
Add events in events page

the information are in the below post links

https://www.linkedin.com/posts/bug-bounty-brigade_bug-bounty-brigade-session-announcement-activity-7079820662319566848-stPW?utm_source=share&utm_medium=member_desktop
https://www.linkedin.com/posts/bug-bounty-brigade_exciting-announcement-join-bug-bounty-activity-7072593202263838721-6kFt?utm_source=share&utm_medium=member_desktop
https://www.linkedin.com/posts/bug-bounty-brigade_exciting-announcement-bug-bounty-101-activity-7071483036957102080-Jw7d?utm_source=share&utm_medium=member_desktop

**Comment by realrohitgurav** [comment]
I've raised a PR for the same. Do let me know if any other changes are required :) Thank you!
