### ISSUE TITLE
add  join this event button

### ISSUE THREAD

**Issue by Mudassirkhan2** [Bug-Bounty-Brigade/Bug-Bounty-Brigade-Main-Website#32]
add  join this event button

if the user clicks on the button redirect him to youtube link of the event 

https://www.youtube.com/@bugbountybrigade/videos

if the event is not their in the youtube just redirect them to the above link 

![Screenshot 2023-10-24 114025](https://github.com/Bug-Bounty-Brigade/Bug-Bounty-Brigade-Main-Website/assets/106579572/b55b5718-149e-471c-982c-c4bbdf668b87)

**Comment by Virtual4087** [comment]
i would like to work on this

**Comment by Mudassirkhan2** [comment]
Please go through Contributing.md for successful PR

**Comment by Mudassirkhan2** [comment]
Button Color #EEB33B  @Virtual4087
