### ISSUE TITLE
Suggest new UI colors according to the logo 

### ISSUE THREAD

**Issue by Mudassirkhan2** [Bug-Bounty-Brigade/Bug-Bounty-Brigade-Main-Website#6]
Suggest new UI colors according to the logo

**Comment by coder-pink** [comment]
@Mudassirkhan2 assign it to me.

**Comment by Mudassirkhan2** [comment]
@coder-pink  assigned it to you

**Comment by Mudassirkhan2** [comment]
> @Mudassirkhan2 assign it to me.

please go through website to know the current design  https://www.bugbountybrigade.tech/

**Comment by coder-pink** [comment]
> > @Mudassirkhan2 assign it to me.
> 
> please go through website to know the current design https://www.bugbountybrigade.tech/

Okay.

**Comment by coder-pink** [comment]
> > @Mudassirkhan2 assign it to me.
> 
> please go through website to know the current design https://www.bugbountybrigade.tech/

@Mudassirkhan2 Done!
