### ISSUE TITLE
add Social Links  and remove facebook icon

### ISSUE THREAD

**Issue by Mudassirkhan2** [Bug-Bounty-Brigade/Bug-Bounty-Brigade-Main-Website#8]
add Social Links to redirect  and open them in the new tab
https://chat.whatsapp.com/IoJp03EGpe5A9ybvbo6VIM
https://youtube.com/@bugbountybrigade?si=7gc17nT4Xvqxr33U
https://www.linkedin.com/company/bug-bounty-brigade/
https://instagram.com/bugbountybrigade?utm_source=qr&igshid=OGIxMTE0OTdkZA==
https://t.me/Resources6969

and delete facebook icon from all pages

**Comment by Vayras** [comment]
hi @Mudassirkhan2 I would like to work on this issue

**Comment by Virtual4087** [comment]
There's no whatsapp option though should we create on ourself?

**Comment by Mudassirkhan2** [comment]
> There's no whatsapp option though should we create on ourself?

Yeah remove Facebook and add WhatsApp

**Comment by Virtual4087** [comment]
an what about links for stuff like discord and twitter? Should we leave it empty?

**Comment by Virtual4087** [comment]
and the svgs at the footer of the page should we make them links too?

**Comment by Virtual4087** [comment]
and is there any link you'd like to provide for "join our community" button?

**Comment by Mudassirkhan2** [comment]
> an what about links for stuff like discord and twitter? Should we leave it empty?

https://twitter.com/BBB_GHC  you can leave empty for the discord currently

**Comment by Mudassirkhan2** [comment]
> and the svgs at the footer of the page should we make them links too?

yes

**Comment by Mudassirkhan2** [comment]
> and is there any link you'd like to provide for "join our community" button?

https://chat.whatsapp.com/IoJp03EGpe5A9ybvbo6VIM

**Comment by Mudassirkhan2** [comment]
> an what about links for stuff like discord and twitter? Should we leave it empty?
> 

https://discord.gg/N73nyWdj

**Comment by Virtual4087** [comment]
done check the pr
